version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_notificacoes
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./docker:/scripts
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 20 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Pass123' -i /scripts/init.sql &&
      wait"
    restart: always

volumes:
  sql_data: