<<<<<<< HEAD
spring.application.name=SistemaNotificacoes
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=notificacao_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SuaSenhaForte

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
=======
# application-example.properties

spring.application.name=SistemaNotificacoes

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=notificacao_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong!Pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
>>>>>>> 7deb3c9 (Ajustando configuracoes do docker)
